services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe
      POSTGRES_PASSWORD: "oJYIZs2D__psEgobLOZN-1Joap6cv_8T"
    volumes:
      - magic_recipe_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "rdHI1NwWdMC3h4KFRdd6CeQA1U94dZ0t"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe_test
      POSTGRES_PASSWORD: "6EWPqPgpQLiDaEhUNp_McVJgP8-dWnHJ"
    volumes:
      - magic_recipe_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "4fTGwzIMbJy48crKfEhc0vi131h3yM19"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  magic_recipe_data:
  magic_recipe_test_data:
